# Project information 项目信息
site_name: STYLAN's Notes
site_url: https://duan-deqing.github.io/notes/
site_author: duan-deqing
site_description: >-
  一个代码和咖啡因浓度差不多的地方。 这里没有正襟危坐的教科书，只有我踩过的坑、焊上的补丁，以及偶尔灵光一闪的“原来如此”。随便翻翻，希望你能笑着带走一句有用的话。

# 显示Repository 仓库
# repo_name: duan-deqing/notes
# repo_url: https://github.com/duan-deqing/notes

# Copyright
copyright: Copyright &copy; 2026 STYLAN

# configuration 配置
theme:
  name: material
  custom_dir: overrides

  features:
    # 设置内容操作按钮
    # - content.action.edit
    # - content.action.view

    # 设置代码操作按钮
    - content.code.annotate
    - content.code.copy
    - content.code.select

    # 设置其他操作按钮
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换至浅色模式
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      # 可选的颜色
      # - primary: 主色
      # - accent: 强调色
      # red        pink       purple     deep-purple
      # indigo     blue       light-blue cyan
      # teal       green      light-green lime
      # yellow     amber      orange     deep-orange
      # brown      grey       blue-grey  black white
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换至深色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换至系统偏好
  # 字体设置
  font:
    text: Roboto Mono
    code: Fira Code
  # 浏览器图标
  favicon: assets/favicon.ico
  # 设置为logo是官方loge
  # 可以使用路径选中自定义的
  icon:
    logo: logo

# 额外配置
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/duan-deqing

# 自定义 CSS
extra_css:
  - stylesheets/extra.css

# 自定义主题配置
extra_javascript:
  - javascripts/extra.js
  - javascripts/mermaid-config.js
  - javascripts/mathjax.js # (2) 你的配置文件，路径稍后解释
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # (3) MathJax CDN

# Extensions 扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  # mermaid 图表
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      type: timeago # 显示为动态格式
      locale: zh # 使用中文显示
      enable_creation_date: true # 启用创建日期的显示

# Navigation 导航
# 读取docs目录下的所有文件，生成导航
nav:
  - 首页: index.md
  # - 关于: about.md
  - Python:
      - 快速开始: _notes/python/01-快速开始.md
      - 变量与基本数据类型: _notes/python/02-变量与基本数据类型.md
      - 容器类型一：列表与元组: _notes/python/03-容器类型一：列表与元组.md
      - 容器类型二：字典与集合: _notes/python/04-容器类型二：字典与集合.md
      - 流程控制：条件与循环: _notes/python/05-流程控制：条件与循环.md
      - 函数: _notes/python/06-函数.md
  - RAG:
      - RAG 实现原理: _notes/rag/rag-getting-started.md
      - RAG 递归到评估: _notes/rag/rag-questions-recursive-to-evaluation.md
  - Langchain:
      - Getting started: _notes/langchain/langchain-getting-started.md
  - Prompt:
      - 风格化图片生成: _notes/prompt/风格化图片生成.md
  - 其他:
      - Linux: _notes/other/linux.md
      - Git: _notes/other/git.md
      - Markdown: _notes/other/markdown.md
